#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"
PKG_DIR="$WORKSPACE_DIR/pkg"

# Ensure Rust toolchain binaries are on PATH
RUSTUP_HOME="${RUSTUP_HOME:-$HOME/.rustup}"
CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
TOOLCHAIN_BIN="$RUSTUP_HOME/toolchains/stable-$(rustc -vV 2>/dev/null | grep host | awk '{print $2}' || echo 'aarch64-apple-darwin')/bin"
export PATH="$CARGO_HOME/bin:$TOOLCHAIN_BIN:$PATH"

# Parse args
PROFILE="release"
if [[ "${1:-}" == "--dev" ]]; then
  PROFILE="dev"
fi

WASM_PACK_MODE="--release"
if [[ "$PROFILE" == "dev" ]]; then
  WASM_PACK_MODE="--dev"
fi

echo "Building WASM crates ($PROFILE)..."

# Build each crate with wasm-bindgen target
for crate_dir in "$WORKSPACE_DIR"/crates/csr-*/; do
  crate_name=$(basename "$crate_dir")

  # Skip csr-shared (it's a library, not a wasm target)
  if [[ "$crate_name" == "csr-shared" ]]; then
    continue
  fi

  echo "  Building $crate_name..."
  wasm-pack build "$crate_dir" \
    --target web \
    $WASM_PACK_MODE \
    --out-dir "$PKG_DIR/$crate_name" \
    --out-name "$crate_name"

  # Remove unnecessary files generated by wasm-pack
  rm -f "$PKG_DIR/$crate_name/.gitignore"
  rm -f "$PKG_DIR/$crate_name/package.json"
done

# Optimize release builds with wasm-opt
if [[ "$PROFILE" == "release" ]] && command -v wasm-opt &>/dev/null; then
  echo "Optimizing with wasm-opt..."
  for wasm_file in "$PKG_DIR"/csr-*/*_bg.wasm; do
    if [[ -f "$wasm_file" ]]; then
      echo "  Optimizing $(basename "$wasm_file")..."
      wasm-opt -O3 --strip-debug "$wasm_file" -o "$wasm_file"
    fi
  done
fi

echo "Done. Output in $PKG_DIR/"
